{{- $project := "snapvibe-application" }}
{{- $destination := "https://kubernetes.default.svc" }}
{{- $repoURL := "https://github.com/Masasak/v1-gitops-manifest.git" }}
{{- $namespace := "snapvibe-service" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  template:
    metadata:
      name: snapvibe-service
    spec:
      project: {{ $project }}
      destination:
        server: {{ $destination }}
        namespace: {{ $namespace }}
      source:
        path: apps
        repoURL: {{ $repoURL }}
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Createnamespace=true
