{{- $project := "snapvibe-application" }}
{{- $destination := "https://kubernetes.default.svc" }}
{{- $repoURL := "https://github.com/Masasak/v1-gitops-manifest.git" }}
{{- $namespace := "snapvibe-service" }}
{{- $imageRegistry := "250832144271.dkr.ecr.ap-northeast-2.amazonaws.com" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  template:
    metadata:
      name: snapvibe-service
    spec:
      project: {{ $project }}
      destination:
        server: {{ $destination }}
        namespace: {{ $namespace }}
      source:
        path: apps
        repoURL: {{ $repoURL }}
        targetRevision: HEAD
        helm:
          values: |
            {{- $map :=
              (dict "spec"
                (dict
                "project" $project
                "destination"
                  (dict "server" $destination "namespace" $namespace)
                "source"
                  (dict "serverPath" "server-spec" "repoURL" $repoURL "targetRevision" "HEAD" "imageRegistry" $imageRegistry)
                )
              )
            }}
            {{- $map := $map | toYaml | nindent 12 }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Createnamespace=true
          - "--creds=argocd-ecr-secret"
