{{- $project := "snapvibe-application" }}
{{- $destination := "https://kubernetes.default.svc" }}
{{- $repoURL := "https://github.com/Masasak/v1-gitops-manifest.git" }}
{{- $namespace := "snapvibe-service" }}
{{- $imageRegistry := "250832144271.dkr.ecr.ap-northeast-2.amazonaws.com" }}
{{- $targetRevision := "HEAD" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: {{ $project }}
  destination:
    server: {{ $destination }}
    namespace: {{ $namespace }}
  source:
    path: apps
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    helm:
      values: |
        {{- $map :=
          (dict "spec"
            (dict
            "project" $project
            "destination"
              (dict "server" $destination)
            "source"
              (dict "serverPath" "server-spec" "repoURL" $repoURL "targetRevision" $targetRevision "imageRegistry" $imageRegistry)
            )
          )
        }}
        {{- $map | toYaml | nindent 12 | toString }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
