name: Update Manifest File
on:
  repository_dispatch:
    types:
      - update_manifest
    
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
          - name: Check Out The Repository
            uses: actions/checkout@v2
            with:
                token: ${{ secrets.gh_token }}
    
          - name: Set Payload Aliases
            id: set_payload
            run: |
              echo "service_name=${{ github.event.client_payload.service_name }}" >> $GITHUB_ENV
              echo "service_prefix=${{ github.event.client_payload.service_prefix }}" >> $GITHUB_ENV
              echo "image_tag=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
              echo "service_port=${{ github.event.client_payload.service_port }}" >> $GITHUB_ENV
      
          - name: Pull Commit 
            run: git pull
    
          - name: Get config file path
            id: config-file
            working-directory: ${{ github.workspace }}
            run: |
              config_file_dir="./apps/resource/${{ env.service_name }}"
              mkdir -p "$config_file_dir"

              config_file_path="$config_file_dir/resource.yaml"
              if [ ! -e "$config_file_path" ]; then
              echo "config file is not exists"
              touch "$config_file_path"          
              yq eval ".config.volume.name = null | \
                      .config.volume.mountPath = null | \
                      .config.volume.secretName = null | \
                      .config.serviceAccount = null | \
                      .config.replicas = 1" -i $config_file_path
              else
              echo "config file is exists"
              fi

              echo "config_file_path=$config_file_path" >> $GITHUB_OUTPUT
    
          - name: Use yq to modify Config file
            working-directory: ${{ github.workspace }}
            run: |
              prefix=''
              if [ -n "${{ env.service_prefix }}" ] && [ "${{ env.service_prefix }}" != "null" ]; then
              prefix='.config.prefix = "${{ env.service_prefix }}"'
              else
              prefix='.config.prefix = null'
              fi

              yq eval -i ".config.serviceName = \"${{ env.service_name }}\" | \
                        .config.imageTag = \"${{ env.image_tag }}\" | \
                        .config.containerPort = ${{ env.service_port }} | \
                        $prefix" -i ${{ steps.config-file.outputs.config_file_path }}
          
          - name: Commit The Chart Realease
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: "update :: ${{ env.service_name }}: Deploy new image ${{ env.image_tag }}"
              commit_options: '--no-verify --signoff'
              branch: main
              skip_checkout: true
              repository: .
              commit_user_name: Masasak-Admin
              commit_user_email: team.Masasak@gmail.com
              commit_author: Masasak-Admin <team.Masasak@gmail.com>